export const handleErr = (success)=>{
    
    try {
        success
    } catch (error) {
        console.log(error);
    }
}